version: "3"

services:
  # Database
  bdd:
    container_name: bdd
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3307:${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: 2554
      DB_SCHEMA: ${MYSQL_DATABASE}
    networks:
      - backend-network

  redis:
     image: redis:latest
     ports:
       - "${REDIS_PORT}:${REDIS_PORT}"
     command: redis-server --requirepass ${REDIS_PASSWORD}
     networks:
      - backend-network

  # Backend Microservices
  authentication-service:
    container_name: authentication-service
    build:
      context: ./server/authentication-service
      dockerfile: Dockerfile
    ports:
      - 7000:${AUTHENTICATION_SERVICE_PORT}
    environment:
      PORT: ${AUTHENTICATION_SERVICE_PORT}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      DB_HOST: bdd
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: root
      DB_PASS: ${MYSQL_ROOT_PASSWORD}
      AUTHENTICATION_SERVICE_URL: http://localhost:${AUTHENTICATION_SERVICE_PORT}
    networks:
      - backend-network
    depends_on:
      - bdd

  payment-service:
    container_name: payment-service
    build:
      context: ./server/payment-service
      dockerfile: Dockerfile
    ports:
      - ${PAYMENT_SERVICE_PORT}:${PAYMENT_SERVICE_PORT}
    environment:
      PORT: ${PAYMENT_SERVICE_PORT}
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: root
      DB_PASS: ${MYSQL_ROOT_PASSWORD}
      PAYMENT_SERVICE_URL: http://localhost:${PAYMENT_SERVICE_PORT}
    networks:
      - backend-network

  common-data-service:
    container_name: common-data-service
    build:
      context: ./server/common-data-service
      dockerfile: Dockerfile
    ports:
      - ${COMMON_DATA_SERVICE_PORT}:${COMMON_DATA_SERVICE_PORT}
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      PORT: ${COMMON_DATA_SERVICE_PORT}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      DB_HOST: bdd
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: root
      DB_PASS: ${MYSQL_ROOT_PASSWORD}
      COMMON_DATA_SERVICE_URL: http://localhost:${COMMON_DATA_SERVICE_PORT}
    networks:
      - backend-network
    depends_on:
      - bdd
   



  search-suggestion-service:
    container_name: search-suggestion-service
    build:
      context: ./server/search-suggestion-service
      dockerfile: Dockerfile
    ports:
      - ${SEARCH_SUGGESTION_SERVICE_PORT}:${SEARCH_SUGGESTION_SERVICE_PORT}
    environment:
      PORT: ${SEARCH_SUGGESTION_SERVICE_PORT}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: root
      DB_PASS: ${MYSQL_ROOT_PASSWORD}
      SEARCH_SUGGESTION_SERVICE_URL: http://localhost:${SEARCH_SUGGESTION_SERVICE_PORT}
    networks:
      - backend-network

  # Frontend
  react-nginx:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-nginx
    ports:
      - ${REACT_APP_PORT}:80
    networks:  
      - backend-network
    environment:
      REACT_CLIENT_URL: ${REACT_CLIENT_URL}
      REACT_APP_ENVIRONMENT: ${REACT_APP_ENVIRONMENT}
    depends_on:
      - common-data-service
      - search-suggestion-service
      - authentication-service


networks:
  backend-network:
    driver: bridge

volumes:
  db_data:
