
FROM maven:3.8.1 as builder

WORKDIR /app


COPY /pom.xml .
RUN mvn clean dependency:go-offline


COPY /src ./src
RUN mvn package -DskipTests


FROM openjdk:11

WORKDIR /app


COPY --from=builder /app/target/common-data-service.jar .


# Exécution de l'application Spring Boot
ENTRYPOINT ["java", "-jar", "common-data-service.jar"]

